name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies (if you later add a requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Lint check (optional)
    - name: Run lint check
      run: |
        python -m pip install flake8
        flake8 . --ignore=E501

    # Build Docker services (validate Docker Compose)
    - name: Build and start Docker services
      run: |
        docker compose up -d --build
        docker compose ps
